### PR TITLE
Add support for Rails/ActiveSupport 7.1

### PR DESCRIPTION
**Pull request by D-system**
This PR add support for Rails/ActiveSupport 7.1

### CODE REVIEW

**Comment by krishantaylor** [comment]
Any word on when this will be released? This was merged a while ago.

**Comment by Floppy** [comment]
good point, thanks for the reminder. I'll get a release out in the next couple of days.

**Comment by D-system** [comment]
I forget out it too haha

**Comment by krishantaylor** [comment]
@Floppy, do you have an updated timeframe for when the release will happen?

**Comment by Floppy** [comment]
v1.4.0 is released now 👍🏻

**Comment by jalada** [comment]
Hey folks, this seems to have caused a regression on my machine whereby https://github.com/Data-Liberation-Front/csvlint.rb/issues/229 resurfaces when using the gem standalone on Ruby 3.3.

**Pull request merged**
