### PR TITLE
Pre commit hook

### LINKED ISSUE #275: Pre-commit integration
### Expected Behaviour

csvlint should have a .pre-commit-hooks.yaml to allow user to leverage pre-commit and run csvlint automatically on commit

### Desired Behaviour 

pre-commit config file and updated readme for usage

https://github.com/belminf/pre-commit-chef/blob/master/.pre-commit-hooks.yaml for example is very similar (in spirit) :

 - look only for specific type of files that are changed by the commit
 - installed via gemspec (https://pre-commit.com/index.html#ruby)
 - exit code to pass or not the hook

If there's interest I wouldn't mind implementing the change, but I'd rather make sure you are on board before implementing it.

### PR DESCRIPTION
**Pull request by jrottenberg**
This PR fixes #275 

Changes proposed in this pull request:

- pre-commit hook config, new file see https://pre-commit.com/index.html#ruby
- Update README to describe usage

### CODE REVIEW

**Comment by Floppy** [comment]
Nice one! Could you add a link to https://pre-commit.com in the README? I wasn't aware of the specific tool, so others may also not be...

**Review by Floppy — APPROVED** [review]

**Comment by jrottenberg** [comment]
Thanks a lot @Floppy ! 
Will you cut a release ? I hinted v1.2.0 the config for the users to start at that version.

Otherwise if they try to use it on `main`:

```
❯ pre-commit run -a
[WARNING] The 'rev' field of repo 'https://github.com/Data-Liberation-Front/csvlint.rb' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Installing environment for https://github.com/Data-Liberation-Front/csvlint.rb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
csvlint..................................................................Passed
```

**Comment by Floppy** [comment]
Yeah, I'll push one out shortly! Thanks :)

**Comment by Floppy** [comment]
release done :)

**Comment by jrottenberg** [comment]
Thanks a lot, we got it on the official list of hooks : 
https://github.com/pre-commit/pre-commit.com/pull/793


https://pre-commit.com/hooks.html 🎉

**Pull request merged**
