### PR TITLE
support ruby 3.1.1

### PR DESCRIPTION
**Pull request by sivteck**
This PR fixes #

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Floppy** [comment]
Thanks! I'm trying to get this building on the current Ruby 2 versions, then will be merging in the 3+ support from this and #249. Bear with me, I'll get it done soon.

**Comment by swrobel** [comment]
@Floppy hate to be annoying, but any progress here? We'd love to help if help is needed.

**Comment by Floppy** [comment]
@swrobel sorry, it's being a royal pain, and spare time is in short supply. I'm trying to work my way up the versions from https://github.com/Data-Liberation-Front/csvlint.rb/pull/259. I will try to get back to it this weekend. 🤞🏻

**Comment by Floppy** [comment]
After a lot of wrangling, Ruby 3 support is finally merged in under #264. Thanks for your work here, it helped me get it all straightened out, even though I didn't merge this PR directly!

**Pull request closed without merging**
