### PR TITLE
Replace colorize with rainbow to make licensing consistent.

### LINKED ISSUE #214: Feature request: remove dependency on GPL-2'ed "colorize" gem
We (Grand Rounds, www.grandrounds.com) would like to use `csvlint` in our own commercial application, which is not and should not be FOSS (at least in  our opinion).  Since we (and AFAICT, the FSF) regard bundling a gem as essentially identical to "linking", we can't use gems that are covered by the full GPL license.  Colorize is licensed under GPL-2 .

### Desired Behaviour (for improvement suggestions only)

Replace use of Colorize with [Rainbow](https://github.com/sickill/rainbow) which is covered by the MIT license. I suggest Rainbow because it appears to be nearly call-compatible, while easier to globally disable/enable (so removing almost every test for `if $stdout.tty?`).

### Your Environment
* Operating System and version (desktop or mobile): Linux (Ubuntu 14.04, 16.04.02LTS), MacOS

### I'm happy to submit a PR for this, working on it.

What would you suggest I use to test cli operation is as good as it was previously? Since the current code tests `$stdout.tty?`, it appears that testing colors may be a bit hacky.

### PR DESCRIPTION
**Pull request by cobbr2**
This PR fixes #214

Changes proposed in this pull request:

- Remove 'colorize' and  use 'rainbow' as production dependencies
- Only enable 'rainbow' if `$stdout.tty?` to keep behavior the same as it was previously

The first commit uses `rainbow/refinements` to make the code as similar to the `colorize` version as possible, but that breaks Ruby-2.0.0 compatibility. Now uses Rainbow's "presenter" style to support all the versions currently configured in Travis.

Using Rainbow introduces a risk for future maintainers: Rainbow colorizes based on a [global setting](https://github.com/sickill/rainbow#configuration).  So if some additional output stream (e.g., a separate warnings output file) were added, *and* the color refinements were called on it, they would be enabled/disabled based on the same flag as the cli uses.

### CODE REVIEW

**Comment by 007** [comment]
Happy Birthday #215!

**Comment by cobbr2** [comment]
Happy New Year, @007 .

**Comment by Floppy** [comment]
🍰

**Comment by cobbr2** [comment]
Happy New Year, @007. Happy 2nd birthday, #215 !

**Comment by Floppy** [comment]
It's on my todo list to sort out ownership and maintenance of this repo - thanks for the ping to remind me to Just Get It Done. And happy birthday #215 indeed. 🍰

**Pull request merged**
